components:
  default:
    merge_strategy: "group_1"
    auto_merge: true
    auto_label: true

  libsahtrace:
    merge_strategy: "individual"

build:

  blacklist:
  - "raspberrypi4-64"

  # linked:
  # - layer: "meta-usp"
