variables:
  BUILD_DEPS: libamxc libamxp libamxd libamxo 
  BUILD_TARGET: lcm-sample-app
  PC_BUILD_PACKAGE: "off"
  PC_DEPLOY_PACKAGE: "off"
  PC_PAGES: "off"
  PC_DOC_GEN: "off"
  PC_CROSS_COMPILATION: "off"

include:
  - remote: 'https://gitlab.com/soft.at.home/ci/gitlab-ci/raw/main/ambiorix-default-pipeline.yml'
