# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

LICENSE_PATH += "${LAYERDIR}/licenses"

BBFILE_COLLECTIONS += "meta-amx"
BBFILE_PATTERN_meta-amx = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-amx = "6"

HOSTTOOLS += "fakeroot"

LAYERDEPENDS_meta-amx = "core"
LAYERSERIES_COMPAT_meta-amx = "scarthgap"
# ATM it's not an essential dependency, only for pcb side of ambiorix
LAYERDEPENDS_meta-amx += "${@bb.utils.contains('LCM_SYSBUS','pcb-bus','meta-pcb','',d)}"

GIT_BASE_URL ?= "gitlab.com/soft.at.home"
