# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

LICENSE_PATH += "${LAYERDIR}/licenses"

BBFILE_COLLECTIONS += "meta-amx"
BBFILE_PATTERN_meta-amx = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-amx = "6"

HOSTTOOLS:append = "fakeroot"

LAYERDEPENDS_meta-amx = "core"
LAYERSERIES_COMPAT_meta-amx = "honister"

GIT_BASE_URL ?= "gitlab.com/soft.at.home"
